version: '3.7'
#THIS environment sets up all of FAS
#  All dependencies -> HSM (vault, hm-collector, kafka), RTS (red fish sims) are all setup and active.
#  The FAS binary is active
#  NO ports are exposed to the local system.
#  This will be used for integration testing
networks:
  smoke:

services:

  smoke_test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./smoke_test.py", "-f","example_smoke.json"]
    depends_on:
      - httpbin
    networks:
      - smoke
  httpbin:
    image:  artifactory.algol60.net/docker.io/kennethreitz/httpbin
    hostname: httpbin
    networks:
      - smoke

