version: '3.7'

networks:
  hms-test:

services:
  tavern_test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tavern","-c", "/src/libs/tavern_global_config_integration_test.yaml","-p","/src/libs"]
    depends_on:
      - httpbin
    networks:
      - hms-test
  smoke_test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["smoke","-f", "/src/libs/example_smoke.json"]
    depends_on:
      - httpbin
    networks:
      - hms-test
  httpbin:
    image:  artifactory.algol60.net/docker.io/kennethreitz/httpbin
    hostname: httpbin
    networks:
      - hms-test

