#!/bin/bash

# MIT License

# (C) Copyright [2019-2021] Hewlett Packard Enterprise Development LP

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

# Main
WORKDIR=${PWD}

# Pull release/shasta-1.4 hms-pytest image from local registry, or DTR as a fallback.
IMAGE="cray/hms-pytest:1.1.1"
LOCAL_TARGET="registry.local/${IMAGE}"
REMOTE_TARGET="dtr.dev.cray.com/${IMAGE}"

# hms-test CT library path containing shared python functions.
HMS_TEST_REPO_DIR="/opt/cray/tests/ncn-resources/hms/hms-test"

IMAGE_PULLED=false
for TARGET in ${LOCAL_TARGET} ${REMOTE_TARGET} ; do
    PULL_CMD="podman pull ${TARGET}"
    echo "Running '${PULL_CMD}'..."
    ${PULL_CMD}
    PULL_RET=$?
    if [[ ${PULL_RET} -eq 0 ]] ; then
        IMAGE_PULLED=true
        break
    fi
done

if ! ${IMAGE_PULLED} ; then
    exit 1
fi

podman run \
    --rm \
    --mount type=bind,src=/opt/cray/tests,dst=/opt/cray/tests,rw=true \
    --mount type=bind,src=/etc/ssl/certs,dst=/etc/ssl/certs,ro=true \
    --mount type=bind,src=/var/lib/ca-certificates/,dst=/var/lib/ca-certificates/,ro=true \
    --env CURL_CA_BUNDLE=/var/lib/ca-certificates/ca-bundle.pem \
    --env PYTHONPATH="${PYTHONPATH}:${HMS_TEST_REPO_DIR}" \
    --workdir ${WORKDIR} \
    ${TARGET} \
    pytest $@