name: Build and Publish hms-test Docker image
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build_and_release:
    uses: Cray-HPE/hms-build-image-workflows/.github/workflows/build_and_release_image.yaml@v2
    with:
      image-name: hms-test
      docker-build-file: Dockerfile
      enable-pr-comment: true
    secrets: inherit
